"""Run the exported PPO policy on the hub. Milestone 5.

Upload robot/policy_weights.py (generated by scripts/export_policy.py)
alongside this file.

Deliberately shaped as a straight swap for robot/benchmark.py -- same launch
ritual, same fixed 10 s window, same statistics -- so the learned policy and
the classical controller are compared on the same measurement rather than on
impressions. Classical baseline on the braced build: 1.50 deg pitch RMS,
3.6 deg peak.

Two decisions worth knowing about:

* **The gyro is fed RAW**, unlike the classical controller, which needs a 30 ms
  low-pass to stay calm. The policy was trained on raw (if noisy) rate in a sim
  that has no structural resonance, so filtering here would feed it an input
  distribution it never saw. Faithful-to-training is the honest first test of
  transfer. If it rings, that is a finding about the sim-to-real gap, not a
  reason to have quietly pre-filtered it.
* **Duty is clamped to MAX_DUTY** anyway, as a safety rail. In sim this policy
  never commands more than 35.7% (mean 12.5%, p99 32.5%), so the clamp should
  never bind -- if the printout says it did, the robot found a state the sim
  never showed it.

Signs were verified against the exported weights before this ever ran: +5 deg
of forward lean gives +0.34 duty, -5 deg gives -0.34, and both wheel terms
carry the same sign as pitch, matching the reference gains.
"""
from pybricks.hubs import TechnicHub
from pybricks.parameters import Axis, Color, Direction, Port
from pybricks.pupdevices import Motor
from pybricks.tools import StopWatch, wait
from umath import radians

# ---- inlined from robot/policy_weights.py (Pybricks runs ONE file) ----
from umath import exp


def tanh(x):
    """Pybricks umath has exp but no tanh, so define it. The clamp keeps
    exp() from overflowing; tanh is saturated to within 1e-7 by |x| = 8."""
    if x > 8.0:
        return 1.0
    if x < -8.0:
        return -1.0
    e = exp(2.0 * x)
    return (e - 1.0) / (e + 1.0)

OBS_SCALE = [3, 0.3, 0.03, 0.03]
W1 = [
    [0.702026, 0.210825, 0.0490765, -0.290482],
    [-0.536413, -0.337735, -0.818831, -0.482263],
    [0.818739, -0.250751, -0.574787, 0.391628],
    [0.285442, -0.16145, -0.465036, 0.187071],
    [-0.285759, 0.0118535, -0.351855, -1.10473],
    [0.0507589, 1.06121, -0.894113, 0.34778],
    [-0.51041, -0.158171, 0.394621, 0.646813],
    [0.484088, 0.445014, 0.607052, 0.770944],
]
B1 = [-0.0246836, 0.0194028, 0.0481925, 0.0841094, -0.0423774, -0.0576672, 0.0147453, -0.008442]
W2 = [
    [-0.350252, 0.815521, -0.849606, -0.0889702, 1.00941, -0.0237481, -0.284465, -0.520465],
    [0.339092, -0.13068, 0.599227, -0.17791, 0.45791, -0.225892, 0.865267, 1.03683],
    [0.0759548, 0.882507, 0.4978, 0.975997, 0.616014, 0.487495, -0.381512, -0.884681],
    [-0.886621, 0.835252, 0.357113, -0.447595, 0.0740154, 0.223131, -0.15694, -0.042196],
    [-0.149801, -0.10169, -0.21321, -0.142485, 0.538318, 0.4588, 0.731603, -1.10374],
    [0.627251, 1.05733, -0.255898, -0.104179, -0.0715865, -0.618766, 0.103864, -0.702901],
    [-0.515474, -0.0943588, -0.0789709, 0.583916, 0.630168, -0.879644, -0.253787, -0.483372],
    [0.1471, 0.162912, 0.531756, -0.609047, 0.812607, -0.268609, -0.765611, -0.998148],
]
B2 = [-0.101992, 0.0327654, 0.0326871, 0.0582376, -0.0247598, 0.061242, 0.0653985, -0.0145624]
W3 = [-0.294023, 0.277826, -0.520645, -0.0622433, -0.203237, -0.232073, -0.116422, -0.524456]
B3 = -0.0058795


def act(state):
    x = [state[i] * OBS_SCALE[i] for i in range(4)]
    h1 = [tanh(sum(W1[j][i] * x[i] for i in range(4)) + B1[j]) for j in range(8)]
    h2 = [tanh(sum(W2[j][i] * h1[i] for i in range(8)) + B2[j]) for j in range(8)]
    u = sum(W3[i] * h2[i] for i in range(8)) + B3
    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)
# ---- end inlined weights ----

hub = TechnicHub(top_side=-Axis.X, front_side=-Axis.Z)
left = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right = Motor(Port.B, Direction.CLOCKWISE)
PITCH_AXIS = -Axis.Y

DT = 5
V_NOM = 7400
FALL_DEG = 45
MAX_DUTY = 40
BENCH_MS = 10000
LOG_EVERY = 4

N_LOG = BENCH_MS // (DT * LOG_EVERY) + 4
p_buf = [0] * N_LOG
d_buf = [0] * N_LOG
w_buf = [0] * N_LOG
w = 0

print("battery mV:", hub.battery.voltage())

# --- time the forward pass before trusting the loop --------------------
watch = StopWatch()
probe = [0.02, 0.1, 0.5, 1.0]
t0 = watch.time()
for _ in range(200):
    act(probe)
us = (watch.time() - t0) * 1000 // 200
print("forward pass:", us, "us of a", DT * 1000, "us budget")
if us > DT * 1000 * 0.5:
    print("WARNING: over half the control period goes to the policy")

# --- RED: wait to be stood up and held still ---------------------------
hub.light.on(Color.RED)
still = 0
while still < 50:
    ok = (hub.imu.acceleration(Axis.Z) > 8000
          and abs(hub.imu.angular_velocity(PITCH_AXIS)) < 2)
    still = still + 1 if ok else 0
    wait(10)

hub.imu.reset_heading(0)
pitch0 = hub.imu.rotation(PITCH_AXIS)
left.reset_angle(0)
right.reset_angle(0)
hub.light.on(Color.GREEN)

watch.reset()
t0 = watch.time()
n = 0
fell_at = -1
sum_sq = 0.0
peak = 0.0
clamped = 0
worst_us = 0

while watch.time() - t0 < BENCH_MS:
    pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
    if abs(pitch) > FALL_DEG:
        fell_at = watch.time() - t0
        break
    la = left.angle()
    ra = right.angle()
    state = [radians(pitch),
             radians(hub.imu.angular_velocity(PITCH_AXIS)),
             radians((la + ra) / 2),
             radians((left.speed() + right.speed()) / 2)]
    a_us = watch.time()
    duty = act(state) * 100
    a_us = watch.time() - a_us
    if a_us > worst_us:
        worst_us = a_us
    if duty > MAX_DUTY:
        duty = MAX_DUTY
        clamped += 1
    elif duty < -MAX_DUTY:
        duty = -MAX_DUTY
        clamped += 1
    out = duty * V_NOM / hub.battery.voltage()
    left.dc(out)
    right.dc(out)

    sum_sq += pitch * pitch
    if abs(pitch) > peak:
        peak = abs(pitch)
    if n % LOG_EVERY == 0 and w < N_LOG:
        p_buf[w] = int(pitch * 10)
        d_buf[w] = int(duty)
        w_buf[w] = int((la + ra) / 2)
        w += 1
    n += 1
    wait(max(0, t0 + DT * n - watch.time()))

left.dc(0)
right.dc(0)
hub.light.on(Color.BLUE)

elapsed = watch.time() - t0
print("fell_at_ms:", fell_at, "elapsed:", elapsed, "steps:", n)
print("rate:", (1000 * n // elapsed) if elapsed else 0, "Hz (want ~200)")
print("worst act() in the loop:", worst_us, "ms tick resolution")
print("duty clamped on", clamped, "of", n, "steps")
if n:
    print("pitch_rms_x100:", int(100 * (sum_sq / n) ** 0.5),
          "peak_x10:", int(10 * peak))
print("t_ms,seg,pitch_x10,duty,wheel_mean")
for i in range(w):
    print(i * DT * LOG_EVERY, 0, p_buf[i], d_buf[i], w_buf[i], sep=",")
print("END")
