"""Run the exported PPO policy on the hub. Milestone 5.

policy_fast.py (generated by scripts/make_fast_policy.py; see robot/README.md
for which policy module is current) is imported below; pybricksdev bundles
imported local modules into the upload automatically. The Q12 fixed-point
form costs 1.6 ms per pass against the 5 ms budget; the float sources in
policies/ cost 13-18 ms and would force the loop down to 69 Hz.

Deliberately shaped as a straight swap for robot/benchmark.py -- same launch
ritual, same fixed window, same statistics -- so the learned policy and the
classical controller are compared on the same measurement rather than on
impressions.

Two decisions worth knowing about:

* **The gyro is FILTERED at RATE_TAU_MS**, and run 16 is why. Faithful-to-
  training said feed it raw, since the policy learned on raw rate in a sim
  with no structural resonance. That was the honest first test and it failed
  loudly: at 200 Hz on raw gyro the policy clamps 47% of its steps and falls
  at 4.0 s, chasing the ~11 Hz drivetrain mode. The same policy with the
  filter ran clean. This is a deviation from training conditions,
  deliberately; the RIGHT fix is the resonance in the simulator, and until
  then the filter is a patch over a known sim-to-real gap.
* **The export chain is verified, not assumed**: tests/test_contracts.py
  checks SB3 -> float export -> Q12 end to end (< 0.003 duty error). The
  +10.8% defect run 22 found lived only in the pipeline-CONTROL's fit and
  never touched this path (run 24 + its correction).

Signs were verified against the exported weights before this ever ran: +5 deg
of forward lean gives positive duty, and both wheel terms carry the same sign
as pitch, matching the reference gains.
"""
from pybricks.parameters import Color
from pybricks.tools import StopWatch, wait
from umath import radians

from hubconfig import (DT, FALL_DEG, MAX_DUTY, PITCH_AXIS, RATE_TAU_MS, V_NOM,
                       make_hub, make_motors, wait_until_upright)
from policy_fast import act

hub = make_hub()
left, right = make_motors()

BENCH_MS = 10000
LOG_EVERY = 4

N_LOG = BENCH_MS // (DT * LOG_EVERY) + 4
p_buf = [0] * N_LOG
d_buf = [0] * N_LOG
w_buf = [0] * N_LOG
w = 0

print("battery mV:", hub.battery.voltage())

# --- time the forward pass before trusting the loop --------------------
watch = StopWatch()
probe = [0.02, 0.1, 0.5, 1.0]
t0 = watch.time()
for _ in range(200):
    act(probe)
us = (watch.time() - t0) * 1000 // 200
print("forward pass:", us, "us of a", DT * 1000, "us budget")
if us > DT * 1000 * 0.5:
    print("WARNING: over half the control period goes to the policy")

hub.light.on(Color.RED)
wait_until_upright(hub)

hub.imu.reset_heading(0)
pitch0 = hub.imu.rotation(PITCH_AXIS)
left.reset_angle(0)
right.reset_angle(0)
hub.light.on(Color.GREEN)

ALPHA = DT / (RATE_TAU_MS + DT)
rate_filt = 0.0

watch.reset()
t0 = watch.time()
n = 0
fell_at = -1
sum_sq = 0.0
sum_p = 0.0
peak = 0.0
clamped = 0
worst_us = 0

while watch.time() - t0 < BENCH_MS:
    pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
    if abs(pitch) > FALL_DEG:
        fell_at = watch.time() - t0
        break
    rate_filt += ALPHA * (hub.imu.angular_velocity(PITCH_AXIS) - rate_filt)
    left_deg = left.angle()
    right_deg = right.angle()
    # The policy's input — the same 4-vector the sim trains on (the contract
    # lives in src/lego_rl/env.py's docstring and in README "The state"):
    #   [ pitch          rad    body lean, + = toward the front face
    #     pitch rate     rad/s  gyro, low-passed at RATE_TAU_MS
    #     wheel angle    rad    mean of both encoders, relative to chassis
    #     wheel speed    rad/s  mean of both encoder speeds            ]
    # act() applies OBS_SCALE internally and returns duty in [-1, 1].
    state = [radians(pitch),
             radians(rate_filt),
             radians((left_deg + right_deg) / 2),
             radians((left.speed() + right.speed()) / 2)]
    a_us = watch.time()
    duty = act(state) * 100
    a_us = watch.time() - a_us
    if a_us > worst_us:
        worst_us = a_us
    if duty > MAX_DUTY:
        duty = MAX_DUTY
        clamped += 1
    elif duty < -MAX_DUTY:
        duty = -MAX_DUTY
        clamped += 1
    out = duty * V_NOM / hub.battery.voltage()
    left.dc(out)
    right.dc(out)

    sum_sq += pitch * pitch
    sum_p += pitch
    if abs(pitch) > peak:
        peak = abs(pitch)
    if n % LOG_EVERY == 0 and w < N_LOG:
        p_buf[w] = int(pitch * 10)
        d_buf[w] = int(duty)
        w_buf[w] = int((left_deg + right_deg) / 2)
        w += 1
    n += 1
    wait(max(0, t0 + DT * n - watch.time()))

left.dc(0)
right.dc(0)
hub.light.on(Color.BLUE)

elapsed = watch.time() - t0
print("fell_at_ms:", fell_at, "elapsed:", elapsed, "steps:", n)
print("rate:", (1000 * n // elapsed) if elapsed else 0, "Hz (want ~200)")
print("worst act() in the loop:", worst_us, "ms tick resolution")
print("duty clamped on", clamped, "of", n, "steps")
if n:
    mean = sum_p / n
    var = sum_sq / n - mean * mean
    print("pitch_rms_x100:", int(100 * (sum_sq / n) ** 0.5),
          "sigma_x100:", int(100 * (var if var > 0 else 0.0) ** 0.5),
          "peak_x10:", int(10 * peak))
print("t_ms,seg,pitch_x10,duty,wheel_mean")
for i in range(w):
    print(i * DT * LOG_EVERY, 0, p_buf[i], d_buf[i], w_buf[i], sep=",")
print("END")
