"""Run the exported PPO policy on the hub. Milestone 4.

Upload robot/policy_weights.py (generated by scripts/export_policy.py)
alongside this file. On start it times the forward pass; if the budget
doesn't fit 200 Hz, fall back to the linear gains from scripts/linearize.py.
"""
from pybricks.hubs import TechnicHub
from pybricks.parameters import Axis, Direction, Port
from pybricks.pupdevices import Motor
from pybricks.tools import StopWatch, wait
from umath import copysign, radians

from policy_weights import act

hub = TechnicHub(top_side=-Axis.X, front_side=-Axis.Z)  # from sysid_directions 2026-08-22
PITCH_AXIS = -Axis.Y
left = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right = Motor(Port.B, Direction.CLOCKWISE)

DT = 5
V_NOM = 7400
FALL_DEG = 45

# --- time the forward pass before trusting the loop ---
watch = StopWatch()
s = [0.02, 0.1, 0.5, 1.0]
for _ in range(100):
    act(s)
print("forward pass:", watch.time() * 10, "us  (budget: 5000 us minus I/O)")

while abs(hub.imu.angular_velocity(PITCH_AXIS)) > 2:
    wait(10)
pitch0 = hub.imu.rotation(PITCH_AXIS)
left.reset_angle(0)
right.reset_angle(0)

watch.reset()
n = 0
while True:
    pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
    if abs(pitch) > FALL_DEG:
        left.dc(0)
        right.dc(0)
        break
    state = [radians(pitch),
             radians(hub.imu.angular_velocity(PITCH_AXIS)),
             radians((left.angle() + right.angle()) / 2),
             radians((left.speed() + right.speed()) / 2)]
    duty = act(state) * 100
    out = V_NOM * (duty + copysign(10, duty)) / hub.battery.voltage()
    left.dc(out)
    right.dc(out)
    n += 1
    wait(max(0, DT * n - watch.time()))
