"""Run the exported PPO policy on the hub. Milestone 5.

Upload robot/policy_weights.py (generated by scripts/export_policy.py)
alongside this file.

Deliberately shaped as a straight swap for robot/benchmark.py -- same launch
ritual, same fixed 10 s window, same statistics -- so the learned policy and
the classical controller are compared on the same measurement rather than on
impressions. Classical baseline on the braced build: 1.50 deg pitch RMS,
3.6 deg peak.

Two decisions worth knowing about:

* **The gyro is FILTERED at 30 ms**, and run 13 is why. Faithful-to-training
  said feed it raw, since the policy learned on raw rate in a sim with no
  structural resonance. That was the honest first test and it failed loudly:
  at 200 Hz on raw gyro the policy clamps 47% of its steps and falls at 4.0 s,
  because nothing in training ever taught it not to chase an 11 Hz mode. The
  same policy with a 30 ms low-pass runs at 1.17 deg RMS with zero clamping --
  6.3x quieter, and the best number this robot has produced. Batteries two
  millivolts apart, so this is the resonance and not the volts.

  This is a deviation from training conditions, deliberately, and the RIGHT
  fix is to put the resonance in the simulator so the policy learns to reject
  it. Until then the filter is a patch over a known sim-to-real gap, which is
  a different thing from a solution.
* **Duty is clamped to MAX_DUTY** anyway, as a safety rail. In sim this policy
  never commands more than 35.7% (mean 12.5%, p99 32.5%), so the clamp should
  never bind -- if the printout says it did, the robot found a state the sim
  never showed it.

Signs were verified against the exported weights before this ever ran: +5 deg
of forward lean gives +0.34 duty, -5 deg gives -0.34, and both wheel terms
carry the same sign as pitch, matching the reference gains.
"""
from pybricks.hubs import TechnicHub
from pybricks.parameters import Axis, Color, Direction, Port
from pybricks.pupdevices import Motor
from pybricks.tools import StopWatch, wait
from umath import radians

from policy_weights import act

hub = TechnicHub(top_side=-Axis.X, front_side=-Axis.Z)
left = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right = Motor(Port.B, Direction.CLOCKWISE)
PITCH_AXIS = -Axis.Y

DT = 5
V_NOM = 7400
FALL_DEG = 45
MAX_DUTY = 40
BENCH_MS = 10000
LOG_EVERY = 4

N_LOG = BENCH_MS // (DT * LOG_EVERY) + 4
p_buf = [0] * N_LOG
d_buf = [0] * N_LOG
w_buf = [0] * N_LOG
w = 0

print("battery mV:", hub.battery.voltage())

# --- time the forward pass before trusting the loop --------------------
watch = StopWatch()
probe = [0.02, 0.1, 0.5, 1.0]
t0 = watch.time()
for _ in range(200):
    act(probe)
us = (watch.time() - t0) * 1000 // 200
print("forward pass:", us, "us of a", DT * 1000, "us budget")
if us > DT * 1000 * 0.5:
    print("WARNING: over half the control period goes to the policy")

# --- RED: wait to be stood up and held still ---------------------------
hub.light.on(Color.RED)
still = 0
while still < 50:
    ok = (hub.imu.acceleration(Axis.Z) > 8000
          and abs(hub.imu.angular_velocity(PITCH_AXIS)) < 2)
    still = still + 1 if ok else 0
    wait(10)

hub.imu.reset_heading(0)
pitch0 = hub.imu.rotation(PITCH_AXIS)
left.reset_angle(0)
right.reset_angle(0)
hub.light.on(Color.GREEN)

watch.reset()
t0 = watch.time()
n = 0
fell_at = -1
sum_sq = 0.0
peak = 0.0
clamped = 0
worst_us = 0

while watch.time() - t0 < BENCH_MS:
    pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
    if abs(pitch) > FALL_DEG:
        fell_at = watch.time() - t0
        break
    la = left.angle()
    ra = right.angle()
    state = [radians(pitch),
             radians(hub.imu.angular_velocity(PITCH_AXIS)),
             radians((la + ra) / 2),
             radians((left.speed() + right.speed()) / 2)]
    a_us = watch.time()
    duty = act(state) * 100
    a_us = watch.time() - a_us
    if a_us > worst_us:
        worst_us = a_us
    if duty > MAX_DUTY:
        duty = MAX_DUTY
        clamped += 1
    elif duty < -MAX_DUTY:
        duty = -MAX_DUTY
        clamped += 1
    out = duty * V_NOM / hub.battery.voltage()
    left.dc(out)
    right.dc(out)

    sum_sq += pitch * pitch
    if abs(pitch) > peak:
        peak = abs(pitch)
    if n % LOG_EVERY == 0 and w < N_LOG:
        p_buf[w] = int(pitch * 10)
        d_buf[w] = int(duty)
        w_buf[w] = int((la + ra) / 2)
        w += 1
    n += 1
    wait(max(0, t0 + DT * n - watch.time()))

left.dc(0)
right.dc(0)
hub.light.on(Color.BLUE)

elapsed = watch.time() - t0
print("fell_at_ms:", fell_at, "elapsed:", elapsed, "steps:", n)
print("rate:", (1000 * n // elapsed) if elapsed else 0, "Hz (want ~200)")
print("worst act() in the loop:", worst_us, "ms tick resolution")
print("duty clamped on", clamped, "of", n, "steps")
if n:
    print("pitch_rms_x100:", int(100 * (sum_sq / n) ** 0.5),
          "peak_x10:", int(10 * peak))
print("t_ms,seg,pitch_x10,duty,wheel_mean")
for i in range(w):
    print(i * DT * LOG_EVERY, 0, p_buf[i], d_buf[i], w_buf[i], sep=",")
print("END")
