"""Generated by scripts/linear_to_net.py -- do not edit.

THIS IS NOT A LEARNED POLICY. It is the classical linear controller
[10.71  0.87  0.43  0.3 ] (Pybricks units) cast into the policy network's
architecture, so that it travels the identical export / fixed-point / hub
pipeline while implementing a control law already validated on hardware.

It is a CONTROL: comparing it against the real classical controller on the
robot separates "the learned policy is worse" from "the pipeline degrades
whatever passes through it".

act(state) -> duty in [-1, 1]; state = [pitch, pitch_rate, wheel_angle,
wheel_rate] in rad and rad/s, sign conventions as in src/lego_rl/env.py.
"""
from umath import exp


def tanh(x):
    """Pybricks umath has exp but no tanh."""
    if x > 8.0:
        return 1.0
    if x < -8.0:
        return -1.0
    e = exp(2.0 * x)
    return (e - 1.0) / (e + 1.0)


OBS_SCALE = [3, 0.3, 0.03, 0.03]
W1 = [
    [-0.192529, -0.0433778, -2.13228, -1.08875],
    [0.232391, 0.302002, 1.65085, 1.27219],
    [0.243563, 0.207654, 1.72319, 1.4087],
    [-0.607858, -0.557067, -0.480776, -0.24435],
    [0.455405, 0.44603, 1.04257, 0.491014],
    [0.565148, 0.56542, 1.49794, 1.21133],
    [-0.409016, -0.232016, -1.11874, -1.2353],
    [-0.641137, -0.368674, -1.53055, -0.387322],
]
B1 = [-0.137742, -0.0909048, -0.0520554, -0.740062, -0.254591, 0.11884, 0.0816562, 0.195932]
W2 = [
    [0.530871, -1.02389, -0.637327, -0.371026, -0.763831, -0.726896, 0.995981, 0.706159],
    [-0.0363689, -0.166887, -0.122978, 0.490036, 0.00670374, -0.0329156, 0.297485, 0.0211824],
    [0.194291, -0.42776, -0.71032, -0.0334892, 0.0119538, 0.0801967, -0.164101, 0.363112],
    [0.0701943, 0.0702147, 0.230673, -0.0287323, 0.302533, 0.365192, -0.314562, -0.279742],
    [-0.0195567, 0.364081, 0.64246, 0.0523881, 0.186229, -0.165223, 0.019392, -0.427493],
    [-1.09423, 1.03294, 0.624108, -0.597276, 0.434685, 0.651567, -0.764984, -0.397801],
    [-0.252817, 0.214887, 0.166858, 0.0593201, 0.318131, 0.468826, -0.797712, -0.195335],
    [-0.422602, 0.888855, 0.438073, -0.127845, 0.76602, 0.793721, -0.91105, -0.472631],
]
B2 = [-0.179517, -0.0666997, -0.325546, -0.203389, 0.112293, 0.138229, -0.0383709, 0.0461774]
W3 = [-0.546969, 0.296461, 0.4848, -0.368695, -0.160516, 0.737181, -0.0334106, 0.307749]
B3 = 0.0595572


def act(state):
    x = [state[i] * OBS_SCALE[i] for i in range(4)]
    h1 = [tanh(sum(W1[j][i] * x[i] for i in range(4)) + B1[j]) for j in range(8)]
    h2 = [tanh(sum(W2[j][i] * h1[i] for i in range(8)) + B2[j]) for j in range(8)]
    u = sum(W3[i] * h2[i] for i in range(8)) + B3
    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)
