#!/usr/bin/env python3
"""Generate robot/_bench_inference.py: five implementations of the same 4-8-8-1
policy, timed against each other ON THE HUB.

13 ms for 104 multiply-accumulates is ~125 us per MAC, which is far too slow to
be arithmetic. In MicroPython every float operation heap-allocates a boxed
object and `sum(<generator>)` builds an iterator per row, so the enemy is
allocation and interpreter dispatch. Each variant removes one source:

  v0  as exported          generators + exp()-based tanh
  v1  unrolled             explicit arithmetic, cached locals, no generators
  v2  unrolled + LUT       tanh from a 257-entry table, linear interpolation
  v3  fixed point + LUT    Q10 integers; small ints are tagged immediates in
                           MicroPython, so this allocates nothing at all.
                           Q10 keeps every product inside 30 bits, which
                           matters: exceeding that promotes to arbitrary
                           precision and gets DRAMATICALLY slower.
  (the @micropython.native emitter is probed separately in
   robot/_probe_native.py -- it is a compile-time decorator, so an
   unsupported emitter breaks the whole module rather than raising)

Every variant is checked against v0 on the hub before its timing is believed --
a fast wrong answer is worth nothing.
"""
from __future__ import annotations

import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEIGHTS = ROOT / "policies" / "policy_weights.py"
OUT = ROOT / "robot" / "_bench_inference.py"

Q = 10          # fixed-point fraction bits
LUT_N = 256     # tanh table entries over [-LUT_X, +LUT_X]
LUT_X = 4.0


def load_weights():
    ns: dict = {}
    src = WEIGHTS.read_text()
    src = re.sub(r"^from umath import exp$", "from math import exp", src, flags=re.M)
    exec(compile(src, "policy_weights.py", "exec"), ns)
    return ns["OBS_SCALE"], ns["W1"], ns["B1"], ns["W2"], ns["B2"], ns["W3"], ns["B3"]


def main() -> None:
    OBS, W1, B1, W2, B2, W3, B3 = load_weights()

    # OBS_SCALE folded into the first layer: 4 fewer multiplies per pass, and
    # it costs nothing because the weights are constants anyway.
    W1s = [[W1[j][i] * OBS[i] for i in range(4)] for j in range(8)]

    lut = [math.tanh(-LUT_X + 2 * LUT_X * i / LUT_N) for i in range(LUT_N + 1)]
    lut_q = [int(round(v * (1 << Q))) for v in lut]
    W1q = [[int(round(v * (1 << Q))) for v in row] for row in W1s]
    B1q = [int(round(v * (1 << Q))) for v in B1]
    W2q = [[int(round(v * (1 << Q))) for v in row] for row in W2]
    B2q = [int(round(v * (1 << Q))) for v in B2]
    W3q = [int(round(v * (1 << Q))) for v in W3]
    B3q = int(round(B3 * (1 << Q)))

    def fmt(x):
        return repr(x)

    L = []
    A = L.append
    A('"""Generated by scripts/make_bench_inference.py -- do not edit."""')
    A("from pybricks.hubs import TechnicHub")
    A("from pybricks.tools import StopWatch")
    A("from umath import exp")
    A("")
    A("hub = TechnicHub()")
    A("watch = StopWatch()")
    A("")
    A(f"OBS = {fmt(OBS)}")
    A(f"W1 = {fmt(W1)}")
    A(f"B1 = {fmt(B1)}")
    A(f"W2 = {fmt(W2)}")
    A(f"B2 = {fmt(B2)}")
    A(f"W3 = {fmt(W3)}")
    A(f"B3 = {fmt(B3)}")
    A(f"W1S = {fmt(W1s)}          # OBS_SCALE folded in")
    A(f"LUT = {fmt(lut)}")
    A(f"LUTQ = {fmt(lut_q)}")
    A(f"W1Q = {fmt(W1q)}")
    A(f"B1Q = {fmt(B1q)}")
    A(f"W2Q = {fmt(W2q)}")
    A(f"B2Q = {fmt(B2q)}")
    A(f"W3Q = {fmt(W3q)}")
    A(f"B3Q = {B3q}")
    A(f"Q = {Q}")
    A(f"LUT_N = {LUT_N}")
    A(f"LUT_X = {LUT_X}")
    A(f"LUT_STEP = {2 * LUT_X / LUT_N!r}")
    A(f"LUT_SCALE = {LUT_N / (2 * LUT_X)!r}   # index = (x + LUT_X) * LUT_SCALE")
    A("")

    # ---- v0: exactly as exported ------------------------------------
    A('''
def tanh(x):
    if x > 8.0:
        return 1.0
    if x < -8.0:
        return -1.0
    e = exp(2.0 * x)
    return (e - 1.0) / (e + 1.0)


def v0(state):
    x = [state[i] * OBS[i] for i in range(4)]
    h1 = [tanh(sum(W1[j][i] * x[i] for i in range(4)) + B1[j]) for j in range(8)]
    h2 = [tanh(sum(W2[j][i] * h1[i] for i in range(8)) + B2[j]) for j in range(8)]
    u = sum(W3[i] * h2[i] for i in range(8)) + B3
    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)
''')

    # ---- v1: unrolled, no generators --------------------------------
    A("\ndef v1(state):")
    A("    a = state[0] * OBS[0]; b = state[1] * OBS[1]")
    A("    c = state[2] * OBS[2]; d = state[3] * OBS[3]")
    A("    h = [0.0] * 8")
    A("    for j in range(8):")
    A("        r = W1[j]")
    A("        h[j] = tanh(r[0] * a + r[1] * b + r[2] * c + r[3] * d + B1[j])")
    A("    g = [0.0] * 8")
    A("    h0 = h[0]; h1 = h[1]; h2 = h[2]; h3 = h[3]")
    A("    h4 = h[4]; h5 = h[5]; h6 = h[6]; h7 = h[7]")
    A("    for j in range(8):")
    A("        r = W2[j]")
    A("        g[j] = tanh(r[0]*h0 + r[1]*h1 + r[2]*h2 + r[3]*h3 +")
    A("                    r[4]*h4 + r[5]*h5 + r[6]*h6 + r[7]*h7 + B2[j])")
    A("    u = (W3[0]*g[0] + W3[1]*g[1] + W3[2]*g[2] + W3[3]*g[3] +")
    A("         W3[4]*g[4] + W3[5]*g[5] + W3[6]*g[6] + W3[7]*g[7] + B3)")
    A("    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)")
    A("")

    # ---- v2: unrolled + tanh LUT, OBS folded ------------------------
    A('''
def tanh_lut(x):
    if x <= -LUT_X:
        return -1.0
    if x >= LUT_X:
        return 1.0
    f = (x + LUT_X) * LUT_SCALE
    i = int(f)
    t = f - i
    a = LUT[i]
    return a + (LUT[i + 1] - a) * t


def v2(state):
    a = state[0]; b = state[1]; c = state[2]; d = state[3]
    h = [0.0] * 8
    for j in range(8):
        r = W1S[j]
        h[j] = tanh_lut(r[0]*a + r[1]*b + r[2]*c + r[3]*d + B1[j])
    h0 = h[0]; h1 = h[1]; h2 = h[2]; h3 = h[3]
    h4 = h[4]; h5 = h[5]; h6 = h[6]; h7 = h[7]
    g = [0.0] * 8
    for j in range(8):
        r = W2[j]
        g[j] = tanh_lut(r[0]*h0 + r[1]*h1 + r[2]*h2 + r[3]*h3 +
                        r[4]*h4 + r[5]*h5 + r[6]*h6 + r[7]*h7 + B2[j])
    u = (W3[0]*g[0] + W3[1]*g[1] + W3[2]*g[2] + W3[3]*g[3] +
         W3[4]*g[4] + W3[5]*g[5] + W3[6]*g[6] + W3[7]*g[7] + B3)
    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)
''')

    # ---- v3: fixed point ---------------------------------------------
    A('''
def v3(state):
    # Q10 throughout. Inputs are the only float->int conversion; after that
    # nothing allocates, because MicroPython small ints are tagged immediates.
    a = int(state[0] * 1024.0); b = int(state[1] * 1024.0)
    c = int(state[2] * 1024.0); d = int(state[3] * 1024.0)
    h = [0] * 8
    for j in range(8):
        r = W1Q[j]
        v = (r[0]*a + r[1]*b + r[2]*c + r[3]*d) >> Q
        v += B1Q[j]
        if v <= -4096:
            h[j] = -1024
        elif v >= 4096:
            h[j] = 1024
        else:
            h[j] = LUTQ[(v + 4096) >> 5]
    h0 = h[0]; h1 = h[1]; h2 = h[2]; h3 = h[3]
    h4 = h[4]; h5 = h[5]; h6 = h[6]; h7 = h[7]
    g = [0] * 8
    for j in range(8):
        r = W2Q[j]
        v = (r[0]*h0 + r[1]*h1 + r[2]*h2 + r[3]*h3 +
             r[4]*h4 + r[5]*h5 + r[6]*h6 + r[7]*h7) >> Q
        v += B2Q[j]
        if v <= -4096:
            g[j] = -1024
        elif v >= 4096:
            g[j] = 1024
        else:
            g[j] = LUTQ[(v + 4096) >> 5]
    u = (W3Q[0]*g[0] + W3Q[1]*g[1] + W3Q[2]*g[2] + W3Q[3]*g[3] +
         W3Q[4]*g[4] + W3Q[5]*g[5] + W3Q[6]*g[6] + W3Q[7]*g[7]) >> Q
    u += B3Q
    if u < -1024:
        u = -1024
    elif u > 1024:
        u = 1024
    return u * 0.0009765625      # 1/1024, back to float duty
''')

    # v4 (native emitter) lives in a SEPARATE file: @micropython.native is a
    # compile-time decorator, so if Pybricks did not build the emitter in, the
    # whole module fails to compile. It cannot be guarded with try/except here.

    # ---- harness ------------------------------------------------------
    A('''
STATE = [0.0873, 0.8727, 0.4, 2.0]      # 5 deg, 50 deg/s, 0.4 rad, 2 rad/s

def bench(fn, name, ref=None, budget_ms=600):
    # warm up, then time however many iterations fit in budget_ms
    fn(STATE)
    n = 0
    t0 = watch.time()
    while watch.time() - t0 < budget_ms:
        fn(STATE); fn(STATE); fn(STATE); fn(STATE)
        fn(STATE); fn(STATE); fn(STATE); fn(STATE)
        n += 8
    dt = watch.time() - t0
    us = dt * 1000 // n
    got = fn(STATE)
    err = "" if ref is None else "  err %.5f" % (got - ref)
    print(name, ":", us, "us/call  (", n, "calls in", dt, "ms )  out", got, err)
    return us, got


print("battery mV:", hub.battery.voltage())
print("state:", STATE)
print("")
base_us, ref = bench(v0, "v0 as-exported ")
bench(v1, "v1 unrolled    ", ref)
bench(v2, "v2 +tanh LUT   ", ref)
bench(v3, "v3 fixed point ", ref)
print("")
print("budget is 5000 us at 200 Hz; as-exported cost", base_us, "us")
print("END")
''')

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
