#!/usr/bin/env python3
"""Generate experimental/ab/_ab_cycle.py: classical vs learned policy, switched back and
forth inside ONE continuous balance.

Run 16 compared four controllers in four separate stand-ups, and the honest
conclusion was that it could not settle anything: classical scored 3.31 deg and
1.56 deg on IDENTICAL configurations at the same voltage. With 2x run-to-run
variance, one 1.17 deg policy segment proves nothing.

The variance almost certainly comes from the things that change between
stand-ups -- how it is released, where it sits on the floor, how the wheels are
loaded. So do not stand up between conditions. Balance once and switch the
controller underneath, repeatedly. Every difference between the conditions then
happens inside the same continuous run, and drift hits both equally. This is a
crossover design, and it turns one measurement into a paired series.

Two details that make the numbers honest:

  * The first SETTLE_MS of each segment is DISCARDED. Switching controllers
    mid-flight causes a transient that belongs to neither of them.
  * The gyro filter state carries across the switch, so the policy is not
    handed a cold filter that the classical controller warmed up.

A fall is not fatal: it re-arms and resumes the cycle where it left off, with
the segment marked. LED green = classical, cyan = policy, red = stand me up.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]   # repo root (this lives in experimental/ab/)

HEADER = '''"""Generated by experimental/ab/make_ab_cycle.py -- do not edit."""
from pybricks.hubs import TechnicHub
from pybricks.parameters import Axis, Color, Direction, Port
from pybricks.pupdevices import Motor
from pybricks.tools import StopWatch, wait

hub = TechnicHub(top_side=-Axis.X, front_side=-Axis.Z)
left = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right = Motor(Port.B, Direction.CLOCKWISE)
PITCH_AXIS = -Axis.Y

K_ANGLE, K_RATE, K_MOTOR, K_SPEED = 10.71, 0.87, 0.43, 0.30
RATE_TAU_MS = 30
MAX_DUTY = 100    # the limit is now an OBSERVATION, not a setting. It was 40,
                  # a number chosen on the unbraced robot from one 2.5 s segment
                  # that saturated 70% of the time (see balance_classical.py).
                  # A sim sweep says 40/60/80/100 are indistinguishable on this
                  # plant (0.80 deg RMS, <0.5% saturation) while hardware run 20
                  # had the net clamping 35-44%. Rather than pick a new arbitrary
                  # number, take the clamp out of the loop and log the duty
                  # HISTOGRAM instead, so what the controller actually asks for
                  # is measured rather than assumed.
DT = 5
V_NOM = 7400
FALL_DEG = 45

SEG_MS = 6000        # per condition
SETTLE_MS = 1200     # discarded at the start of each segment
CYCLES = 7           # 7 x 3 conditions x 6 s = about 2 minutes

# kind: 0 = classical gains computed directly
#       1 = the SAME law cast into the net and quantised (pipeline control)
#       2 = the learned policy
#
# Condition 1 is the point. Every previous hardware comparison confounded "the
# learned policy is worse" with "the export/fixed-point/hub pipeline degrades
# whatever passes through it". A network that IS the classical controller
# travels the identical pipeline while implementing a law already measured at
# 1.5-3.3 deg RMS, so 0 vs 1 isolates the pipeline and 1 vs 2 isolates the
# policy. In sim they are indistinguishable (10.00s/100% both, 0.88 vs 0.69
# deg RMS); this asks the same question on hardware.
KINDS = (0, 1, 2)
COLORS = (Color.GREEN, Color.YELLOW, Color.CYAN)
ALPHA = DT / (RATE_TAU_MS + DT)
DEG2RAD = 0.0174532925

print("battery mV:", hub.battery.voltage())
# mean_x100 and sigma_x100 are the point of this revision. Run 20's rms_x100 was
# taken about the ARM-TIME pitch reference, and that reference drifts (~0.2 deg/s
# of uncorrected gyro bias; the hub is never stationary long enough for Pybricks
# to re-zero it). The controller absorbs the false tilt by walking the wheel out
# along K_ANGLE*pitch + K_MOTOR*wheel = 0, so rms ended up tracking wheel angle
# at r=0.999 and carried almost no information about oscillation.
#   mean  = the drift itself (and any real lean)
#   sigma = RMS about the segment mean = the oscillation, drift-immune
print("seg,cycle,kind,battery_mV,rms_x100,mean_x100,sigma_x100,peak_x10,"
      "clamp_pct,dmax,wheel,fell,rate_hz")
'''

BODY = '''

def arm():
    """Wait to be stood up and held still. Returns the pitch reference."""
    left.dc(0)
    right.dc(0)
    hub.light.on(Color.RED)
    still = 0
    while still < 50:
        ok = (hub.imu.acceleration(Axis.Z) > 8000
              and abs(hub.imu.angular_velocity(PITCH_AXIS)) < 2)
        still = still + 1 if ok else 0
        wait(10)
    hub.imu.reset_heading(0)
    left.reset_angle(0)
    right.reset_angle(0)
    return hub.imu.rotation(PITCH_AXIS)


pitch0 = arm()
watch = StopWatch()
rate_f = 0.0          # carried across switches on purpose
n = 0
seg = 0

for cyc in range(CYCLES):
    # ABBA. In run 20 every cycle ran the conditions in the same order, so the
    # second condition always carried 6 s more accumulated reference drift than
    # the first -- and the drift grew monotonically all run. That alone produced
    # a "10/10" result. Alternating the order each cycle makes the drift a
    # common-mode term instead of a per-condition one.
    order = range(len(KINDS)) if cyc % 2 == 0 else range(len(KINDS) - 1, -1, -1)
    for ki in order:
        kind = KINDS[ki]
        hub.light.on(COLORS[ki])
        batt = hub.battery.voltage()
        t0 = watch.time()
        k = 0            # per-segment time base; a global counter broke the
                         # ring test by making every deadline already past
        sum_p = 0.0
        sum_sq = 0.0
        peak = 0.0
        dmax = 0.0       # largest duty the law ASKED for, before any clamp
        clamped = 0
        hist = [0] * 10  # |commanded duty| in 10% bins; bin 9 = 90% and over
        m = 0
        fell = 0
        while watch.time() - t0 < SEG_MS:
            pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
            rate_f += ALPHA * (hub.imu.angular_velocity(PITCH_AXIS) - rate_f)
            if abs(pitch) > FALL_DEG:
                fell = 1
                break
            la = left.angle()
            ra = right.angle()
            angle = (la + ra) / 2
            speed = (left.speed() + right.speed()) / 2
            if kind == 0:
                duty = (K_ANGLE * pitch + K_RATE * rate_f
                        + K_MOTOR * angle + K_SPEED * speed)
            elif kind == 1:
                duty = act_lin([pitch * DEG2RAD, rate_f * DEG2RAD,
                                angle * DEG2RAD, speed * DEG2RAD]) * 100
            else:
                duty = act([pitch * DEG2RAD, rate_f * DEG2RAD,
                            angle * DEG2RAD, speed * DEG2RAD]) * 100
            ad = duty if duty > 0 else -duty
            if duty > MAX_DUTY:
                duty = MAX_DUTY
            elif duty < -MAX_DUTY:
                duty = -MAX_DUTY
            # Clamp AFTER the battery scaling, not before. out = duty*V_NOM/V can
            # exceed 100 whenever the battery sits below V_NOM, and Pybricks then
            # clips it silently -- an unlogged, battery-dependent limit that
            # differs between conditions if one asks for more duty. Clamp it here
            # so the limit is always the one we counted.
            out = duty * V_NOM / hub.battery.voltage()
            hit = 0
            if out > 100:
                out = 100
                hit = 1
            elif out < -100:
                out = -100
                hit = 1
            left.dc(out)
            right.dc(out)
            # statistics only AFTER the switching transient has passed
            if watch.time() - t0 > SETTLE_MS:
                sum_p += pitch
                sum_sq += pitch * pitch
                if abs(pitch) > peak:
                    peak = abs(pitch)
                if ad > dmax:
                    dmax = ad
                b = int(ad * 0.1)
                hist[9 if b > 9 else b] += 1
                clamped += hit      # counted over the same window as the rest
                m += 1
            n += 1
            k += 1
            wait(max(0, t0 + DT * k - watch.time()))
        if m:
            mean = sum_p / m
            rms = int(100 * (sum_sq / m) ** 0.5)
            # RMS about the segment mean. Drift shifts the mean, not the spread,
            # so this is the number that survives a drifting pitch reference.
            v = sum_sq / m - mean * mean
            sigma = int(100 * (v ** 0.5)) if v > 0 else 0
        else:
            mean = 0.0
            rms = -1
            sigma = -1
        rate_hz = (1000 * k // (watch.time() - t0)) if watch.time() > t0 else 0
        print(seg, ",", cyc, ",", kind, ",", batt, ",", rms, ",",
              int(100 * mean), ",", sigma, ",",
              int(10 * peak), ",", (100 * clamped // (m + 1)), ",",
              int(dmax), ",",
              int((left.angle() + right.angle()) / 2), ",", fell,
              ",", rate_hz)
        print("H", ",", seg, ",", kind, ",", hist[0], ",", hist[1], ",",
              hist[2], ",", hist[3], ",", hist[4], ",", hist[5], ",",
              hist[6], ",", hist[7], ",", hist[8], ",", hist[9])
        seg += 1
        if fell:
            left.dc(0)
            right.dc(0)
            hub.light.on(Color.BLUE)
            wait(500)
            pitch0 = arm()
            rate_f = 0.0

left.dc(0)
right.dc(0)
hub.light.on(Color.BLUE)
print("END")
'''


def main() -> None:
    import sys
    # --pipeline: two conditions only, classical direct vs the same law through
    # the net. Both hold station, so the run does not degrade -- the three-way
    # version dragged the robot away every third segment via the learned
    # policy's weak position gain and yielded only 2 clean cycles of 7.
    pipeline_only = "--pipeline" in sys.argv

    def grab(name, fn):
        src = re.sub(r'^""".*?"""\n', "", (ROOT / "robot" / name).read_text(),
                     count=1, flags=re.S)
        # both modules define act(); rename one so they can coexist
        src = src.replace("def act(", f"def {fn}(")
        src = src.replace("LUT_act", "LUT_" + fn)
        return src

    linear = grab("policy_linear_fast.py", "act_lin")
    header, body = HEADER, BODY
    if pipeline_only:
        header = (header.replace("KINDS = (0, 1, 2)", "KINDS = (0, 1)")
                        .replace("COLORS = (Color.GREEN, Color.YELLOW, Color.CYAN)",
                                 "COLORS = (Color.GREEN, Color.YELLOW)")
                        .replace("CYCLES = 7           # 7 x 3 conditions x 6 s = about 2 minutes",
                                 "CYCLES = 10          # 10 x 2 conditions x 6 s = about 2 minutes"))
        # the learned policy is not inlined at all in this mode
        body = body.replace("""            else:
                duty = act([pitch * DEG2RAD, rate_f * DEG2RAD,
                            angle * DEG2RAD, speed * DEG2RAD]) * 100
""", "")
        pol = ("\n# ---- the classical law cast into the same net (Q12) ----\n"
               + linear + "# ---- end policy ----\n")
    else:
        learned = grab("policy_fast.py", "act")
        pol = ("\n# ---- learned policy (Q12) ----\n" + learned
               + "\n# ---- the classical law cast into the same net (Q12) ----\n"
               + linear + "# ---- end policies ----\n")
    out = ROOT / "experimental" / "ab" / "_ab_cycle.py"
    out.write_text(header + pol + body)
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
