#!/usr/bin/env python
"""Export the PPO policy mean network (4->8->8->1 tanh) to a pure-Python
weights file MicroPython can import. Time it on the hub with
robot/balance_policy.py before trusting the 200 Hz loop; if it doesn't fit,
distill to the linear gains from scripts/linearize.py instead."""
import argparse
from pathlib import Path

import numpy as np
from stable_baselines3 import PPO

from lego_rl.env import OBS_SCALE


def fmt(a):
    a = np.asarray(a, dtype=float)
    if a.ndim == 1:
        return "[" + ", ".join(f"{v:.6g}" for v in a) + "]"
    return "[\n" + ",\n".join("    " + fmt(r) for r in a) + ",\n]"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("model_path")
    ap.add_argument("--out", default="policies/policy_weights.py")
    args = ap.parse_args()

    model = PPO.load(args.model_path, device="cpu")
    pol = model.policy
    seq = pol.mlp_extractor.policy_net  # Linear, Tanh, Linear, Tanh
    W1, b1 = seq[0].weight.detach().numpy(), seq[0].bias.detach().numpy()
    W2, b2 = seq[2].weight.detach().numpy(), seq[2].bias.detach().numpy()
    W3, b3 = pol.action_net.weight.detach().numpy(), pol.action_net.bias.detach().numpy()

    out = Path(args.out)
    out.write_text(f'''"""Generated by scripts/export_policy.py -- do not edit.
act(state) -> duty in [-1, 1].
state = [pitch, pitch_rate, wheel_angle, wheel_rate] in rad / rad/s,
sign conventions as in src/lego_rl/env.py."""
from umath import exp


def tanh(x):
    """Pybricks umath has exp but no tanh, so define it. The clamp keeps
    exp() from overflowing; tanh is saturated to within 1e-7 by |x| = 8."""
    if x > 8.0:
        return 1.0
    if x < -8.0:
        return -1.0
    e = exp(2.0 * x)
    return (e - 1.0) / (e + 1.0)

OBS_SCALE = {fmt(OBS_SCALE)}
W1 = {fmt(W1)}
B1 = {fmt(b1)}
W2 = {fmt(W2)}
B2 = {fmt(b2)}
W3 = {fmt(W3[0])}
B3 = {float(b3[0]):.6g}


def act(state):
    x = [state[i] * OBS_SCALE[i] for i in range(4)]
    h1 = [tanh(sum(W1[j][i] * x[i] for i in range(4)) + B1[j]) for j in range(8)]
    h2 = [tanh(sum(W2[j][i] * h1[i] for i in range(8)) + B2[j]) for j in range(8)]
    u = sum(W3[i] * h2[i] for i in range(8)) + B3
    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)
''')
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
