#!/usr/bin/env python3
"""Generate robot/_ab_cycle.py: classical vs learned policy, switched back and
forth inside ONE continuous balance.

Run 16 compared four controllers in four separate stand-ups, and the honest
conclusion was that it could not settle anything: classical scored 3.31 deg and
1.56 deg on IDENTICAL configurations at the same voltage. With 2x run-to-run
variance, one 1.17 deg policy segment proves nothing.

The variance almost certainly comes from the things that change between
stand-ups -- how it is released, where it sits on the floor, how the wheels are
loaded. So do not stand up between conditions. Balance once and switch the
controller underneath, repeatedly. Every difference between the conditions then
happens inside the same continuous run, and drift hits both equally. This is a
crossover design, and it turns one measurement into a paired series.

Two details that make the numbers honest:

  * The first SETTLE_MS of each segment is DISCARDED. Switching controllers
    mid-flight causes a transient that belongs to neither of them.
  * The gyro filter state carries across the switch, so the policy is not
    handed a cold filter that the classical controller warmed up.

A fall is not fatal: it re-arms and resumes the cycle where it left off, with
the segment marked. LED green = classical, cyan = policy, red = stand me up.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = '''"""Generated by scripts/make_ab_cycle.py -- do not edit."""
from pybricks.hubs import TechnicHub
from pybricks.parameters import Axis, Color, Direction, Port
from pybricks.pupdevices import Motor
from pybricks.tools import StopWatch, wait

hub = TechnicHub(top_side=-Axis.X, front_side=-Axis.Z)
left = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right = Motor(Port.B, Direction.CLOCKWISE)
PITCH_AXIS = -Axis.Y

K_ANGLE, K_RATE, K_MOTOR, K_SPEED = 10.71, 0.87, 0.43, 0.30
RATE_TAU_MS = 30
MAX_DUTY = 40
DT = 5
V_NOM = 7400
FALL_DEG = 45

SEG_MS = 6000        # per condition
SETTLE_MS = 1200     # discarded at the start of each segment
CYCLES = 10          # 10 x 2 conditions x 6 s = about 2 minutes

# kind: 0 = classical (filtered), 1 = learned policy (filtered)
KINDS = (0, 1)
COLORS = (Color.GREEN, Color.CYAN)
ALPHA = DT / (RATE_TAU_MS + DT)
DEG2RAD = 0.0174532925

print("battery mV:", hub.battery.voltage())
print("seg,cycle,kind,battery_mV,rms_x100,peak_x10,clamp_pct,wheel,fell,rate_hz")
'''

BODY = '''

def arm():
    """Wait to be stood up and held still. Returns the pitch reference."""
    left.dc(0)
    right.dc(0)
    hub.light.on(Color.RED)
    still = 0
    while still < 50:
        ok = (hub.imu.acceleration(Axis.Z) > 8000
              and abs(hub.imu.angular_velocity(PITCH_AXIS)) < 2)
        still = still + 1 if ok else 0
        wait(10)
    hub.imu.reset_heading(0)
    left.reset_angle(0)
    right.reset_angle(0)
    return hub.imu.rotation(PITCH_AXIS)


pitch0 = arm()
watch = StopWatch()
rate_f = 0.0          # carried across switches on purpose
n = 0
seg = 0

for cyc in range(CYCLES):
    for ki in range(len(KINDS)):
        kind = KINDS[ki]
        hub.light.on(COLORS[ki])
        batt = hub.battery.voltage()
        t0 = watch.time()
        k = 0            # per-segment time base; a global counter broke the
                         # ring test by making every deadline already past
        sum_sq = 0.0
        peak = 0.0
        clamped = 0
        m = 0
        fell = 0
        while watch.time() - t0 < SEG_MS:
            pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
            rate_f += ALPHA * (hub.imu.angular_velocity(PITCH_AXIS) - rate_f)
            if abs(pitch) > FALL_DEG:
                fell = 1
                break
            la = left.angle()
            ra = right.angle()
            angle = (la + ra) / 2
            speed = (left.speed() + right.speed()) / 2
            if kind == 0:
                duty = (K_ANGLE * pitch + K_RATE * rate_f
                        + K_MOTOR * angle + K_SPEED * speed)
            else:
                duty = act([pitch * DEG2RAD, rate_f * DEG2RAD,
                            angle * DEG2RAD, speed * DEG2RAD]) * 100
            hit = 0
            if duty > MAX_DUTY:
                duty = MAX_DUTY
                hit = 1
            elif duty < -MAX_DUTY:
                duty = -MAX_DUTY
                hit = 1
            out = duty * V_NOM / hub.battery.voltage()
            left.dc(out)
            right.dc(out)
            # statistics only AFTER the switching transient has passed
            if watch.time() - t0 > SETTLE_MS:
                sum_sq += pitch * pitch
                if abs(pitch) > peak:
                    peak = abs(pitch)
                clamped += hit      # counted over the same window as the rest
                m += 1
            n += 1
            k += 1
            wait(max(0, t0 + DT * k - watch.time()))
        rms = int(100 * (sum_sq / m) ** 0.5) if m else -1
        rate_hz = (1000 * k // (watch.time() - t0)) if watch.time() > t0 else 0
        print(seg, ",", cyc, ",", kind, ",", batt, ",", rms, ",",
              int(10 * peak), ",", (100 * clamped // (m + 1)), ",",
              int((left.angle() + right.angle()) / 2), ",", fell,
              ",", rate_hz)
        seg += 1
        if fell:
            left.dc(0)
            right.dc(0)
            hub.light.on(Color.BLUE)
            wait(500)
            pitch0 = arm()
            rate_f = 0.0

left.dc(0)
right.dc(0)
hub.light.on(Color.BLUE)
print("END")
'''


def main() -> None:
    pol = (ROOT / "robot" / "policy_fast.py").read_text()
    pol = re.sub(r'^""".*?"""\n', "", pol, count=1, flags=re.S)
    out = ROOT / "robot" / "_ab_cycle.py"
    out.write_text(HEADER
                   + "\n# ---- inlined robot/policy_fast.py (Q12, ~1.6 ms) ----\n"
                   + pol + "# ---- end policy ----\n" + BODY)
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
