#!/usr/bin/env python3
"""Generate robot/_ab_test.py: classical vs learned policy, one battery.

The fast policy regressed on the robot (RMS 2.43 -> 8.06 deg, fell at 5.5 s)
after being made 11x faster and reaching its design rate of 200 Hz. Two
explanations were live and the run could not separate them:

  resonance   at 69 Hz the slow policy was accidentally low-passed; at 200 Hz
              it responds to the ~11 Hz structural ring, on RAW gyro, having
              been trained in a sim with no resonance in it
  torque      the battery had fallen to 7918 mV against 8340-8472 for the
              classical baseline, and the duty clamp fired on 22% of steps

So: four segments, one upload, one battery. Segment 4 repeats segment 1, which
brackets any battery drift -- if classical scores the same at both ends the
comparison is clean, and if it does not, the session is thrown out rather than
published with a confound in it.

Auto-rearm between segments, because the policy already falls inside 10 s and
a fall must not cost us the later controllers.

After each measured window the classical controller keeps the robot up,
blinking, until it is picked up. The first version cut the motors the instant
the 10 s elapsed, which drops a balancing robot on the floor and reads to the
operator as "it fell" -- three of four segments in run 16 were reported as
falls when the hub's own log said they survived.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = '''"""Generated by scripts/make_ab_test.py -- do not edit.

Four 10 s segments on one battery, auto-rearming between them.
LED: RED = stand it up and hold still, GREEN/YELLOW/CYAN/WHITE = running.
"""
from pybricks.hubs import TechnicHub
from pybricks.parameters import Axis, Color, Direction, Port
from pybricks.pupdevices import Motor
from pybricks.tools import StopWatch, wait

hub = TechnicHub(top_side=-Axis.X, front_side=-Axis.Z)
left = Motor(Port.A, Direction.COUNTERCLOCKWISE)
right = Motor(Port.B, Direction.CLOCKWISE)
PITCH_AXIS = -Axis.Y

K_ANGLE, K_RATE, K_MOTOR, K_SPEED = 10.71, 0.87, 0.43, 0.30
RATE_TAU_MS = 30
MAX_DUTY = 40
DT = 5
V_NOM = 7400
FALL_DEG = 45
SEG_MS = 10000

# (label, kind, filter_gyro)  kind: 0 = classical, 1 = learned policy
SEGS = (
    ("classical_a  ", 0, 1),
    ("policy_raw   ", 1, 0),
    ("policy_filt  ", 1, 1),
    ("classical_b  ", 0, 1),
)
COLORS = (Color.GREEN, Color.YELLOW, Color.CYAN, Color.WHITE)
ALPHA = DT / (RATE_TAU_MS + DT)
DEG2RAD = 0.0174532925

print("battery mV:", hub.battery.voltage())
print("label,battery_mV,rate_hz,rms_x100,peak_x10,clamp_pct,lasted_ms,fell")
'''

BODY = '''

for si in range(len(SEGS)):
    label, kind, filt = SEGS[si]

    # ---- RED: wait to be stood up and held still ----
    left.dc(0)
    right.dc(0)
    hub.light.on(Color.RED)
    still = 0
    while still < 50:
        ok = (hub.imu.acceleration(Axis.Z) > 8000
              and abs(hub.imu.angular_velocity(PITCH_AXIS)) < 2)
        still = still + 1 if ok else 0
        wait(10)

    hub.imu.reset_heading(0)
    pitch0 = hub.imu.rotation(PITCH_AXIS)
    left.reset_angle(0)
    right.reset_angle(0)
    hub.light.on(COLORS[si])

    batt = hub.battery.voltage()
    watch = StopWatch()
    t0 = watch.time()
    n = 0
    rate_f = 0.0
    sum_sq = 0.0
    peak = 0.0
    clamped = 0
    fell = 0

    while watch.time() - t0 < SEG_MS:
        pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
        rate_raw = hub.imu.angular_velocity(PITCH_AXIS)
        rate_f += ALPHA * (rate_raw - rate_f)
        rate = rate_f if filt else rate_raw
        if abs(pitch) > FALL_DEG:
            fell = 1
            break
        la = left.angle()
        ra = right.angle()
        angle = (la + ra) / 2
        speed = (left.speed() + right.speed()) / 2
        if kind == 0:
            duty = (K_ANGLE * pitch + K_RATE * rate
                    + K_MOTOR * angle + K_SPEED * speed)
        else:
            duty = act([pitch * DEG2RAD, rate * DEG2RAD,
                        angle * DEG2RAD, speed * DEG2RAD]) * 100
        if duty > MAX_DUTY:
            duty = MAX_DUTY
            clamped += 1
        elif duty < -MAX_DUTY:
            duty = -MAX_DUTY
            clamped += 1
        out = duty * V_NOM / hub.battery.voltage()
        left.dc(out)
        right.dc(out)
        sum_sq += pitch * pitch
        if abs(pitch) > peak:
            peak = abs(pitch)
        n += 1
        wait(max(0, t0 + DT * n - watch.time()))

    lasted = watch.time() - t0

    # Measurement over -- but do NOT just cut the motors on a robot that is
    # currently balancing, which drops it on the floor and reads to the
    # operator as "it fell". Keep it up, blink, and wait to be picked up.
    if not fell:
        hold = watch.time()
        while watch.time() - hold < 15000:
            pitch = hub.imu.rotation(PITCH_AXIS) - pitch0
            if abs(pitch) > FALL_DEG or hub.imu.acceleration(Axis.Z) < 6000:
                break          # caught, lifted, or genuinely toppled
            rate_f += ALPHA * (hub.imu.angular_velocity(PITCH_AXIS) - rate_f)
            la = left.angle()
            ra = right.angle()
            duty = (K_ANGLE * pitch + K_RATE * rate_f
                    + K_MOTOR * (la + ra) / 2
                    + K_SPEED * (left.speed() + right.speed()) / 2)
            if duty > MAX_DUTY:
                duty = MAX_DUTY
            elif duty < -MAX_DUTY:
                duty = -MAX_DUTY
            left.dc(duty * V_NOM / hub.battery.voltage())
            right.dc(duty * V_NOM / hub.battery.voltage())
            n2 = (watch.time() - hold) // 250
            hub.light.on(Color.BLUE if n2 % 2 else COLORS[si])
            wait(DT)

    left.dc(0)
    right.dc(0)
    hub.light.on(Color.BLUE)
    rate_hz = (1000 * n // lasted) if lasted else 0
    rms = int(100 * (sum_sq / n) ** 0.5) if n else 0
    print(label, ",", batt, ",", rate_hz, ",", rms, ",", int(10 * peak),
          ",", (100 * clamped // n) if n else 0, ",", lasted, ",", fell)
    wait(800)

print("END")
'''


def main() -> None:
    pol = (ROOT / "robot" / "policy_fast.py").read_text()
    pol = re.sub(r'^""".*?"""\n', "", pol, count=1, flags=re.S)
    out = ROOT / "robot" / "_ab_test.py"
    out.write_text(HEADER
                   + "\n# ---- inlined robot/policy_fast.py (Q12, ~1.6 ms) ----\n"
                   + pol
                   + "# ---- end policy ----\n"
                   + BODY)
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
