#!/usr/bin/env python3
"""Export a policies/*.py float network for pybricks.experimental.MLP.

Reads the W1/B1/W2/B2/W3/B3 + OBS_SCALE module format produced by
scripts/export_policy.py, folds OBS_SCALE into the first layer, and writes a
deployable robot/ module holding the topology, the little-endian float32
weight blob, and an act() wrapper with the same clamp semantics as the
source module. The generated module needs the custom firmware in
firmware/README.md — stock Pybricks has no pybricks.experimental.MLP.

Usage: python firmware/export_mlp_blob.py [policy_weights] [policy_mlp]
"""

import re
import sys
import types
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent

SELF_CHECK_STATES = 200


def load_policy_module(src_name):
    """Exec a policies/*.py module with its hub-only umath import shimmed,
    same trick as scripts/make_fast_policy.load()."""
    src = re.sub(r"^from umath import exp$", "from math import exp",
                 (ROOT / "policies" / f"{src_name}.py").read_text(), flags=re.M)
    mod = types.SimpleNamespace()
    exec(compile(src, f"{src_name}.py", "exec"), mod.__dict__)
    return mod


def main():
    src_name = sys.argv[1] if len(sys.argv) > 1 else "policy_weights"
    out_name = sys.argv[2] if len(sys.argv) > 2 else "policy_mlp"

    mod = load_policy_module(src_name)

    obs_scale = np.asarray(mod.OBS_SCALE, np.float32)
    w1 = np.asarray(mod.W1, np.float32) * obs_scale[None, :]
    b1 = np.asarray(mod.B1, np.float32)
    w2 = np.asarray(mod.W2, np.float32)
    b2 = np.asarray(mod.B2, np.float32)
    w3 = np.asarray(mod.W3, np.float32).reshape(1, -1)
    b3 = np.asarray([mod.B3], np.float32)

    topology = (w1.shape[1], w1.shape[0], w2.shape[0], 1)
    blob = np.concatenate(
        [w1.ravel(), b1, w2.ravel(), b2, w3.ravel(), b3]
    ).astype("<f4").tobytes()

    # Self-check: recompute the forward pass from the blob and compare with
    # the source module's act() over random states.
    rng = np.random.default_rng(0)
    states = rng.uniform(-1, 1, (SELF_CHECK_STATES, topology[0])).astype(np.float32)
    worst = 0.0
    for s in states:
        h1 = np.tanh(w1 @ s + b1)
        h2 = np.tanh(w2 @ h1 + b2)
        u = float((w3 @ h2 + b3)[0])
        u = min(1.0, max(-1.0, u))
        worst = max(worst, abs(u - mod.act(list(map(float, s)))))
    assert worst < 1e-5, f"blob disagrees with {src_name}.act by {worst}"

    out_path = ROOT / "robot" / f"{out_name}.py"
    out_path.write_text(
        f'"""Generated by firmware/export_mlp_blob.py from policies/{src_name}.py'
        f''' -- do not edit.

act(state) -> duty in [-1, 1], same contract as policies/{src_name}.act().
OBS_SCALE is folded into the first layer, so state is raw
[pitch, pitch_rate, wheel_angle, wheel_rate] in rad / rad/s.

Requires the custom firmware with pybricks.experimental.MLP
(see firmware/README.md). Weights: little-endian float32, per layer the
weight matrix (row major) then the biases."""
from pybricks.experimental import MLP

TOPOLOGY = {topology}
WEIGHTS = {blob!r}

_net = MLP(TOPOLOGY, WEIGHTS, output_activation="linear")


def act(state):
    u = _net(state)
    return -1.0 if u < -1.0 else (1.0 if u > 1.0 else u)
'''
    )
    print(f"wrote {out_path.relative_to(ROOT)}: topology {topology}, "
          f"{len(blob)} weight bytes, self-check err {worst:.2e}")


if __name__ == "__main__":
    main()
